### ISSUE TITLE
I am interested in this game

### ISSUE THREAD

**Issue by Shimmer66** [juanpeter/Escape-The-Room#1]
Hello, what are the rules of this game?

**Comment by Shimmer66** [comment]
Sorry, I should study the code carefully.
Now, I get it.

**Comment by juanpeter** [comment]
No, you are right, this code need a good README.md for documentation, I'll be making one right away.
Thank you so much for your interest in my little project!

**Comment by juanpeter** [comment]
Documentation added, closing the issue.
